# Modbus通信設定
DEFAULT_RS485_PORT_NAME = "/dev/ttyACM0"
DEFAULT_USB_PORT_NAME = "/dev/ttyUSB0"
DEFAULT_PORT_NAME = DEFAULT_RS485_PORT_NAME
DEFAULT_BAUDRATE = 9600
DEFAULT_UNIT_ID = 1

# --- 設定 ---
DB_NAME = "sensor_data.db"
