name = "mimamori-bot"
main = "src/index.js"
compatibility_date = "2025-10-21"

# 1時間ごとのスケジュール設定
[triggers]
crons = ["0 * * * *"] # 毎時0分に実行

# KV Namespace Binding
[[kv_namespaces]]
binding = "DATA_KV"
id = "<your-kv-namespace-id>"
